name: DolphinBot CI/CD

on:
  push:
    branches: [ main ]
    paths-ignore:
      - "**.md"
  pull_request:
    branches: [ main ]
    paths-ignore:
      - "**.md"
      
# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  valid:
    runs-on: ubuntu-latest
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
     - uses: actions/checkout@v3
     - name: Set up JDK
       uses: actions/setup-java@v5.6.0
       with:
          java-version: '17'
          distribution: 'temurin'
     - name: Build with maven
       run: mvn clean package

     - name: Upload JAR file
       uses: actions/upload-artifact@v2
       with:
          name: DolphinBot Latest Build
          path: target/*.jar
